name: Build firmware

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]


jobs:
  build-firmware:
    runs-on: ubuntu-latest
    name: Build firmware
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build --pull --build-arg APT_MIRROR="http://azure.archive.ubuntu.com/ubuntu/"

      - name: Run docker container
        run: docker compose up

      - name: Check for build success of all services
        # https://stackoverflow.com/questions/29568352/using-docker-compose-with-ci-how-to-deal-with-exit-codes-and-daemonized-linked
        run: >
          docker-compose ps -aq |
          xargs docker inspect -f '{{ .State.ExitCode }}' |
          grep -v '^0' |
          wc -l |
          tr -d ' '
          || exit 1

      - name: Upload firmwares as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dds-sweeper-firmware-${{ github.sha }}
          if-no-files-found: error
          path: |
            build_*/dds-sweeper/*.uf2
            LICENSE

  github-release:
    name: Github Release
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && contains(github.ref, '/tags') && github.repository_owner == 'QTC-UMD')
    needs: [build-firmware]
    permissions:
      packages: read
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dds-sweeper-firmware-${{ github.sha }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          generate_release_notes: true
          files: |
            LICENSE
            build_rp2040/dds-sweeper/dds-sweeper_rp2040.uf2
            build_rp2350/dds-sweeper/dds-sweeper_rp2350.uf2